aliases:
    cdfleek: cd ~/projects/ublue/fleek
    fleeks: cd ~/.config/home-manager
    ublue: cd ~/projects/ublue
    bluefin: cd ~/projects/ublue/bluefin
bling: high
ejected: false
name: My Fleek Configuration
packages:
    - helix
    - go
    - gcc
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
repo: git@github.com/my/homeconfig
shell: bash
systems:
    - arch: x86_64
      git:
        email: bketelsen@gmail.com
        name: Brian Ketelsen
      hostname: ghanima
      os: linux
      username: bjk
    - arch: aarch64
      git:
        email: bketelsen@gmail.com
        name: Brian Ketelsen
      hostname: chapterhouse
      os: darwin
      username: bjk
    - arch: x86_64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
      hostname: fedora
      os: linux
      username: bjk
unfree: true
