aliases:
    bluefin: cd ~/projects/ublue/bluefin
    cdfleek: cd ~/projects/ublue/fleek
    fleeks: cd ~/.config/home-manager
    gcb: git checkout -b
    gitmain: git checkout main && git pull
    projects: cd ~/projects
    ublue: cd ~/projects/ublue
bling: high
branch: ""
ejected: false
flakedir: .config/home-manager
name: Brians Fleek Configuration
packages:
    - go
    - gcc
    - nodejs
    - yarn
    - rustup
    - vhs
    - emacs
    - dive
paths:
    - $HOME/bin
    - $HOME/.local/bin
    - $HOME/go/bin
programs:
    - dircolors
repo: git@github.com:bketelsen/fleeks
shell: zsh
systems:
    - arch: aarch64
      git:
        email: bketelsen@gmail.com
        name: Brian Ketelsen
        privatekey: ""
      hostname: chapterhouse
      os: darwin
      username: bjk
    - arch: x86_64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
        privatekey: ""
      hostname: fedora
      os: linux
      username: bjk
    - arch: aarch64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
        privatekey: ""
      hostname: f84d89911e5d.ant.amazon.com
      os: darwin
      username: brianjk
    - arch: x86_64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
        privatekey: ""
      hostname: ubluenix
      os: linux
      username: bjk
    - arch: x86_64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
        privatekey: ""
      hostname: fedora
      os: linux
      username: briank
    - arch: x86_64
      git:
        email: Brian Ketelsen
        name: bketelsen@gmail.com
        privatekey: .ssh/id_rsa
      hostname: ghanima
      os: linux
      username: bjk
unfree: true
